// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: pricing.proto
#ifndef GRPC_pricing_2eproto__INCLUDED
#define GRPC_pricing_2eproto__INCLUDED

#include "pricing.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace grpc_pricer {

// Définition du service
class GrpcPricer final {
 public:
  static constexpr char const* service_full_name() {
    return "grpc_pricer.GrpcPricer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status PriceAndDeltas(::grpc::ClientContext* context, const ::grpc_pricer::PricingInput& request, ::grpc_pricer::PricingOutput* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_pricer::PricingOutput>> AsyncPriceAndDeltas(::grpc::ClientContext* context, const ::grpc_pricer::PricingInput& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_pricer::PricingOutput>>(AsyncPriceAndDeltasRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_pricer::PricingOutput>> PrepareAsyncPriceAndDeltas(::grpc::ClientContext* context, const ::grpc_pricer::PricingInput& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_pricer::PricingOutput>>(PrepareAsyncPriceAndDeltasRaw(context, request, cq));
    }
    virtual ::grpc::Status HelloWorld(::grpc::ClientContext* context, const ::grpc_pricer::Empty& request, ::grpc_pricer::ReqInfo* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_pricer::ReqInfo>> AsyncHelloWorld(::grpc::ClientContext* context, const ::grpc_pricer::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_pricer::ReqInfo>>(AsyncHelloWorldRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_pricer::ReqInfo>> PrepareAsyncHelloWorld(::grpc::ClientContext* context, const ::grpc_pricer::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_pricer::ReqInfo>>(PrepareAsyncHelloWorldRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void PriceAndDeltas(::grpc::ClientContext* context, const ::grpc_pricer::PricingInput* request, ::grpc_pricer::PricingOutput* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PriceAndDeltas(::grpc::ClientContext* context, const ::grpc_pricer::PricingInput* request, ::grpc_pricer::PricingOutput* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void HelloWorld(::grpc::ClientContext* context, const ::grpc_pricer::Empty* request, ::grpc_pricer::ReqInfo* response, std::function<void(::grpc::Status)>) = 0;
      virtual void HelloWorld(::grpc::ClientContext* context, const ::grpc_pricer::Empty* request, ::grpc_pricer::ReqInfo* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpc_pricer::PricingOutput>* AsyncPriceAndDeltasRaw(::grpc::ClientContext* context, const ::grpc_pricer::PricingInput& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpc_pricer::PricingOutput>* PrepareAsyncPriceAndDeltasRaw(::grpc::ClientContext* context, const ::grpc_pricer::PricingInput& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpc_pricer::ReqInfo>* AsyncHelloWorldRaw(::grpc::ClientContext* context, const ::grpc_pricer::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpc_pricer::ReqInfo>* PrepareAsyncHelloWorldRaw(::grpc::ClientContext* context, const ::grpc_pricer::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status PriceAndDeltas(::grpc::ClientContext* context, const ::grpc_pricer::PricingInput& request, ::grpc_pricer::PricingOutput* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_pricer::PricingOutput>> AsyncPriceAndDeltas(::grpc::ClientContext* context, const ::grpc_pricer::PricingInput& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_pricer::PricingOutput>>(AsyncPriceAndDeltasRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_pricer::PricingOutput>> PrepareAsyncPriceAndDeltas(::grpc::ClientContext* context, const ::grpc_pricer::PricingInput& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_pricer::PricingOutput>>(PrepareAsyncPriceAndDeltasRaw(context, request, cq));
    }
    ::grpc::Status HelloWorld(::grpc::ClientContext* context, const ::grpc_pricer::Empty& request, ::grpc_pricer::ReqInfo* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_pricer::ReqInfo>> AsyncHelloWorld(::grpc::ClientContext* context, const ::grpc_pricer::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_pricer::ReqInfo>>(AsyncHelloWorldRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_pricer::ReqInfo>> PrepareAsyncHelloWorld(::grpc::ClientContext* context, const ::grpc_pricer::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_pricer::ReqInfo>>(PrepareAsyncHelloWorldRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void PriceAndDeltas(::grpc::ClientContext* context, const ::grpc_pricer::PricingInput* request, ::grpc_pricer::PricingOutput* response, std::function<void(::grpc::Status)>) override;
      void PriceAndDeltas(::grpc::ClientContext* context, const ::grpc_pricer::PricingInput* request, ::grpc_pricer::PricingOutput* response, ::grpc::ClientUnaryReactor* reactor) override;
      void HelloWorld(::grpc::ClientContext* context, const ::grpc_pricer::Empty* request, ::grpc_pricer::ReqInfo* response, std::function<void(::grpc::Status)>) override;
      void HelloWorld(::grpc::ClientContext* context, const ::grpc_pricer::Empty* request, ::grpc_pricer::ReqInfo* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::grpc_pricer::PricingOutput>* AsyncPriceAndDeltasRaw(::grpc::ClientContext* context, const ::grpc_pricer::PricingInput& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::grpc_pricer::PricingOutput>* PrepareAsyncPriceAndDeltasRaw(::grpc::ClientContext* context, const ::grpc_pricer::PricingInput& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::grpc_pricer::ReqInfo>* AsyncHelloWorldRaw(::grpc::ClientContext* context, const ::grpc_pricer::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::grpc_pricer::ReqInfo>* PrepareAsyncHelloWorldRaw(::grpc::ClientContext* context, const ::grpc_pricer::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_PriceAndDeltas_;
    const ::grpc::internal::RpcMethod rpcmethod_HelloWorld_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status PriceAndDeltas(::grpc::ServerContext* context, const ::grpc_pricer::PricingInput* request, ::grpc_pricer::PricingOutput* response);
    virtual ::grpc::Status HelloWorld(::grpc::ServerContext* context, const ::grpc_pricer::Empty* request, ::grpc_pricer::ReqInfo* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_PriceAndDeltas : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PriceAndDeltas() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_PriceAndDeltas() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PriceAndDeltas(::grpc::ServerContext* /*context*/, const ::grpc_pricer::PricingInput* /*request*/, ::grpc_pricer::PricingOutput* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPriceAndDeltas(::grpc::ServerContext* context, ::grpc_pricer::PricingInput* request, ::grpc::ServerAsyncResponseWriter< ::grpc_pricer::PricingOutput>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_HelloWorld : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_HelloWorld() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_HelloWorld() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HelloWorld(::grpc::ServerContext* /*context*/, const ::grpc_pricer::Empty* /*request*/, ::grpc_pricer::ReqInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHelloWorld(::grpc::ServerContext* context, ::grpc_pricer::Empty* request, ::grpc::ServerAsyncResponseWriter< ::grpc_pricer::ReqInfo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_PriceAndDeltas<WithAsyncMethod_HelloWorld<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_PriceAndDeltas : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PriceAndDeltas() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc_pricer::PricingInput, ::grpc_pricer::PricingOutput>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc_pricer::PricingInput* request, ::grpc_pricer::PricingOutput* response) { return this->PriceAndDeltas(context, request, response); }));}
    void SetMessageAllocatorFor_PriceAndDeltas(
        ::grpc::MessageAllocator< ::grpc_pricer::PricingInput, ::grpc_pricer::PricingOutput>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::grpc_pricer::PricingInput, ::grpc_pricer::PricingOutput>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_PriceAndDeltas() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PriceAndDeltas(::grpc::ServerContext* /*context*/, const ::grpc_pricer::PricingInput* /*request*/, ::grpc_pricer::PricingOutput* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PriceAndDeltas(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc_pricer::PricingInput* /*request*/, ::grpc_pricer::PricingOutput* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_HelloWorld : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_HelloWorld() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc_pricer::Empty, ::grpc_pricer::ReqInfo>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc_pricer::Empty* request, ::grpc_pricer::ReqInfo* response) { return this->HelloWorld(context, request, response); }));}
    void SetMessageAllocatorFor_HelloWorld(
        ::grpc::MessageAllocator< ::grpc_pricer::Empty, ::grpc_pricer::ReqInfo>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::grpc_pricer::Empty, ::grpc_pricer::ReqInfo>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_HelloWorld() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HelloWorld(::grpc::ServerContext* /*context*/, const ::grpc_pricer::Empty* /*request*/, ::grpc_pricer::ReqInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* HelloWorld(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc_pricer::Empty* /*request*/, ::grpc_pricer::ReqInfo* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_PriceAndDeltas<WithCallbackMethod_HelloWorld<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_PriceAndDeltas : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PriceAndDeltas() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_PriceAndDeltas() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PriceAndDeltas(::grpc::ServerContext* /*context*/, const ::grpc_pricer::PricingInput* /*request*/, ::grpc_pricer::PricingOutput* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_HelloWorld : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_HelloWorld() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_HelloWorld() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HelloWorld(::grpc::ServerContext* /*context*/, const ::grpc_pricer::Empty* /*request*/, ::grpc_pricer::ReqInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_PriceAndDeltas : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PriceAndDeltas() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_PriceAndDeltas() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PriceAndDeltas(::grpc::ServerContext* /*context*/, const ::grpc_pricer::PricingInput* /*request*/, ::grpc_pricer::PricingOutput* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPriceAndDeltas(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_HelloWorld : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_HelloWorld() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_HelloWorld() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HelloWorld(::grpc::ServerContext* /*context*/, const ::grpc_pricer::Empty* /*request*/, ::grpc_pricer::ReqInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHelloWorld(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PriceAndDeltas : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PriceAndDeltas() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PriceAndDeltas(context, request, response); }));
    }
    ~WithRawCallbackMethod_PriceAndDeltas() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PriceAndDeltas(::grpc::ServerContext* /*context*/, const ::grpc_pricer::PricingInput* /*request*/, ::grpc_pricer::PricingOutput* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PriceAndDeltas(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_HelloWorld : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_HelloWorld() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->HelloWorld(context, request, response); }));
    }
    ~WithRawCallbackMethod_HelloWorld() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HelloWorld(::grpc::ServerContext* /*context*/, const ::grpc_pricer::Empty* /*request*/, ::grpc_pricer::ReqInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* HelloWorld(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PriceAndDeltas : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PriceAndDeltas() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::grpc_pricer::PricingInput, ::grpc_pricer::PricingOutput>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::grpc_pricer::PricingInput, ::grpc_pricer::PricingOutput>* streamer) {
                       return this->StreamedPriceAndDeltas(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PriceAndDeltas() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PriceAndDeltas(::grpc::ServerContext* /*context*/, const ::grpc_pricer::PricingInput* /*request*/, ::grpc_pricer::PricingOutput* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPriceAndDeltas(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::grpc_pricer::PricingInput,::grpc_pricer::PricingOutput>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_HelloWorld : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_HelloWorld() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::grpc_pricer::Empty, ::grpc_pricer::ReqInfo>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::grpc_pricer::Empty, ::grpc_pricer::ReqInfo>* streamer) {
                       return this->StreamedHelloWorld(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_HelloWorld() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status HelloWorld(::grpc::ServerContext* /*context*/, const ::grpc_pricer::Empty* /*request*/, ::grpc_pricer::ReqInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHelloWorld(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::grpc_pricer::Empty,::grpc_pricer::ReqInfo>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_PriceAndDeltas<WithStreamedUnaryMethod_HelloWorld<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_PriceAndDeltas<WithStreamedUnaryMethod_HelloWorld<Service > > StreamedService;
};

}  // namespace grpc_pricer


#endif  // GRPC_pricing_2eproto__INCLUDED
